dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - secure: 0T7wxUFkoyNTOOfeloq7/zGL/J/lJjBkfqHEBHMFXTKsqKtO2U9oekDpH3UVRfbf8uAuaEIviwkFP9/zelC/NHeVitTCbzOwjMBjfDXYzOwSvF0e7h6GU3jnDwA4vqU/nhhtTXGWg2/j7yp5K8kfmI67w/hzOrROImCac5UxCZN8l9TDw8oWGJoNyEM6ctG6fmpr+oHl7byPxjAvz0b+sfQ3jyfUMaBLKvzyI06cgdGBfkPvwX9HtVCo3RIeop3UxAGiJzLM6tm/q7goCyOhcOHO6SF41/Jxhj2M79kWMiDKekzGYAlfmwFCBkWMNDkwSd924p/igUYGRmwC/sBEmvas8pKcKMKXXNhQHU4abtHU53YSPeHpUbXsBl0JFJUoPm8cG4yZQ9OaJ+So59I8Y8cmeSYfRcfNetSmjRKZ3lx4Wd40AYH51ZmcUPe2QnDY2fZk3Ie0wyX3zofNt3tE4Qrq9vVhU97tSp2ETdjX0/OccKSfWwlX/wmQLmLBM9tDtrOYe16Trf5wWNHtkvVbSSby3EJII2KuJqgHNy+XgYj6BeaxyxOIayrwndqfDgHQUbYvpnljH1mB8RvFyZ5w6IWCW/XDAg2h6MAWqhAVafMFAG6LtcIafEZOdeQ5S6umFzRxOEIxaZFPJ/BobcNRIgmhoqydLx10BRxzkGaiXZs=
  - secure: 2QyQUhrFOs/NQ8EjZWH/VgyWyWEvzpxZzxXyUmCapAIQKq2CCCt7bx5wnfeNbXlBdHDJF9XBoRSpZu/cYVAzD5H7ZMVZOp/o9zfOfCE+YX+gyu9xSpdkaMLjrpTvAGnEkgTAbXNO683m9j19ayLhEnyQ/udma78reM3z+DXau9CMMqyRm+MZVxC19/EeOQNrnZixz2ikBqORFqcEa5/bq2LelQdXcO0HAbYBBHmYXUiSkOA6v4Gao00za6S8X5xC/8RYugvaHAJMju7715Ej5nxNtnxD7cCEkhZSR0/2uYbZ/T2fOvRH2R6LbDhL7H8nV9Gul+ATxlCA4k2yd7LJss7L1oXrsDcDEzbR9m46UVy0Xspnqqy080DUuPzOi1t7ermBEBHnnLUby7kDWo8v2Aw4Bfn4wFav3QxzVexAaIbCid/yghkmEA1Z4hd9CD9qo05756Cd8xNSoJXHagy90+KqpkpgkyKEgLAQbVPwTMGQh+ReRO29JyqcgjtmZAyNWWVZ/oKtzPIoCcQgbVTb4C22DQeUc3xdQ3iTJU+LyPEmCqqV+v/cXxQTH54s1fCvTrF7zHckXcYzuQsNukXBwmhMSSH/PFc25rRKp1ZUvEvvSgp+D2LDU6tHDCazZ2dH7zGgCnWnwpr/1EL/9JponEjZCJRqqpqidfRLQ7CAPqE=
  - secure: rWN7ozvNlU1rFMFIfuHknMfeDPFiIUjj1H0tt4TE5nEd66FLq98E/P1QjduS6Ynu7wNYFWhhCpzCaKPpc03+YBP0itrVl5wyPXmX8YUd86hDyS+4NHa7vpNVVoD31S3LnsZHanTgZgwI+1hy6ACSYySAh7PCI+38KwO6Ivqgi0hlzE9ByLHhEV1Ds55nOzpWABDp1Xa8+3pUHkMwAVsjGt8mz0YLwbuSOUXfhuDPcnqTvWxtOiEhs5sxArZpE6LfIh9GKSmzWzVRmtc9AD5Km/HsBIr0N9CydyAEs8LscxQOyxmU+g/FhdtKXkfDtlBUcX1T1VaimvvS794/Fo1dPDKEvNw2H+znul556fjAzx6PKcd4AZIOVKEax/W8OIRmga/2zzmUESYydLv6iLd9BRwlM+/DJvw2mkd8ma/yn4X1npxRi6d5K3yYyXRF16NJ4M9foH++LyKPQMAviOjYNI4j7UVRgNa78KiTDMHSnBNk4DlLcdTTYlZQiXB7wNars9+RuBXMg2QXczKYu23jbLRHKuwlkOK8QskzkyftEj0aO9sVhIonDFcMSf/Qx7BiyE/Ni2U3NR7jUW3FaebVEfuon7bQ3bwbccBs9x4ambdZZ+EH0XsH+I9uZcPZ+OpnLQT6C4tbXKCKCm8GOTn2vAfZeumDgYqKlYLbEoOFKyY=
  - secure: x2c8+2pdCbTHNKStcsYPuR2oCzWIrpsgDhbQZfDeGvf1dinjNz2gRm10ulJT/D/oUH109XxAzcqo8SruPnQbpBSFJd4EHJ5mX/PVtxOtrHDdAQ+OJI2kcq5PrbnO2ZjMoJ6z4IZk7umPm+3ZikObW95kHSL3alYFgho2n1eVYB5EM7ft2hTcX7bC3GwBEg1ylUoUic8Ksm8u40v0OXNcxLQTB7Z0djVlXgytdkj8JxWCvnbLRBM9RP5TyCccsX2GaT6zWe9cA5gwavXNTpXNJ9/kxTHgzTy6ScGC7GrL6LLRBwWLXQ5cu3pVy8wU8cIuWOoVGay62PMlDjhoANQQoNEft8fUQhNWWt3FMSBOK2I4oZLcWut/7uSglbh/mW5XdusJY8cD7rN47fVHqRkYcYXjz4U/o8WxZqJVgxgGtmN2v8Uv+ZqQptaUQ1d9KzKR0EJPfmQKnccbuib4F/KJykgXb5Wg9Gddb2sVOrK7PvP3Uc9uQoN/bKRlRwgLtJxFe9BdfyfJ86wzqIvcVcPbC5FhwZ+h+3F+4xaSpbbsAlVxgKbDNgZwLPUFlCHifTpirQTk1qXzlnJHu8BLXkt4aXfp3KGNfY+X99NfV2cnNLb+2t1YLfOl8QKXfklDmXAuvKFqZxJwNs4pcTIVx6GGFumQbd62f54/1tuGLKRaizY=
install:
- nvm install 6.9.3
- npm install -g typescript
script: bash travis-build.bash
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
    secure: clIMjBlNiofkdmGc4Dv/aOrm+kzys0S3nf4ct2OcutjgKn48nfM4x4ee7gI0D5GrIzQTK4yWwvbUjaBaP82XXPmUcyeZvz0RVIzVrPwAJsJGCdI4zsuBp6X2PtFJd0cLUtu4co8KPXQzYqEOGDCLzE/YCMztEaAep4F89rWoJACbMTL/+F1kLZGGEc7ji67O7+u4AprOwfm1VhDj5DXoUQAgIHFGcKN2k+AfBFEo3DLzUU9mrHgCiyz1Tp9wfpnR9ETArpjjnWAtOZMkv9/fbygAP5Ba+WzJPBT/oW1GvMrxGEnie0CbIXznKKxeXYEStK7ib573h4i+rnHPCcTy/ef25wnch3kVxVncEv1mCxewK2+1XjSu7S8gMkZVd4cPtNuBelA1uteAVjvnTJwv5qmNqEOPSIIDGbhImjmL5ysemLL2mHEMzT1HYd6h1fzEU9rVvSXaWnNyO9CSGUNjqEr0AXWlQZpFybpImgIftPvfXQbl7lf+vVfId7qO86qf+SV83ucjOnkdf05dK/4a1GJta5vUXeRitgVdrtJOJXzueITVr0RpoTd1utAiTHyTbaXdakOxYx6KA5sd9qIglnjAyoOEuVBPNzZ19+Dp0oVhtyv66zFvoeWfq7Pe1RHdDE9GAsysiYk+QVNJVcCE8KqhmFG1N5fvYts0dKuA5Ag=
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
after_deploy:
- bash npm-publish.bash $TRAVIS_TAG
